rm_serial:
  ros__parameters:
    device_name: "/dev/ttyACM2"
    baud_rate: 115200
    flow_control: "none"
    parity: "none"
    stop_bits: "1"
    send_header: 0xA5      # 发送帧头
    receive_header: 0x5A   # 接收帧头
